### ISSUE TITLE
mAP 계산할 때 val 폴더 별로 계산하고, Wandb 수정

### ISSUE THREAD

**Issue by youngjae-avikus** [avikus-ai/detect_train#18]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and found no similar feature requests.

### Description

Batch01에 따른 Validation이 여러 폴더로 이뤄졌는데, 낮은 mAP일 때 어떤 것이 주요한 원인인지 보려고 함

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by youngjae-avikus** [comment]
재연코드 
```bash
python val.py \
    --data \
    data/eo-slicing.yaml \
    --weights \
    slicing_best.pt \
    --device \
    1 \
    --imgsz \
    1280 
```
```yaml
...
val: 
  - /data/2023-EO_SINGLE_CLASS_train/2939/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/ccnuri/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/flicker/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/GORAE/221020/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/GORAE/221026/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/GORAE/221028/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/hannara/busan/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/hannara/incheon_arriving/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/hannara/incheon_berth/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/KHOPE/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/lvis_oid/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_10/eo1/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_10/eo2/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_10/eo3/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_11/eo1/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_11/eo2/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/maersk/2023-01-15_11/eo3/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/objects_365/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/YMwinner/images/val/
  - /data/2023-EO_SINGLE_CLASS_train/youtube/images/val/
nc: 1
names: ['Vessel']
```
